"""
Django settings for auth_server project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xll*fm2g8u*&d-@wy_+u)sf3mze6_34&gx32zq)b)6mik(*xx0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'oidc_provider',  # Agregado
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'auth_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # <--- Verifica que esté tu carpeta 'templates'
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auth_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Configuraciones de OIDC Provider
OIDC_USERINFO = 'auth_server.views.oidc_userinfo'
#OIDC_RSA_PRIVATE_KEY = None  # Si no defines manualmente, se genera una clave
#OIDC_RSA_KEY_FOLDER = os.path.join(BASE_DIR, 'oidc_keys')  # Carpeta para guardar las claves RSA
#OIDC_EXTRA_SCOPE_CLAIMS = 'auth_server.claims.MyScopeClaims'  # Opcional, para scopes adicionales
OIDC_RSA_PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDjwrfarxvUxCW2
rZuBqVYxMlSBAYrbN8A3oTp0hbvF/WJWyK3Kvxeqo5mdrDiSiposGmo0YuD918ZQ
dLnf7sXsoRuUBCcRuBkZ/pHB4ltqX84TxaV/fmrsO+4I6tK/byC4uSZGtjR372OA
dN53lcZv8hINLGRcBzFFb6bD6/rX3H11Ld53ckpACI3qVCBDgqogM5JzXnTM4G06
Vzwo4y/Z20QBdfFBszCa9zbEbKy+nBd1zICA9AoQXwQ6gZnF1tasziQ9cczIeJxZ
t1YL5z6+NJlU+HMTaZ0RQc61LnPxkjkxORmvKrfPGjBnFQRM9Euk4iPgedpBVa96
y/pQf8KRAgMBAAECggEAA1QDbG5QoXb4TMdpVVIMe2Lj5JAJimiHJjOfRLf2Os9t
Z3KT747ZTAS1/Z2C+h6NCttGoAYDNFJkiHpxg48xVI2KIfXpkuhgyDDLH80spCJK
7Z5ewRKE13eMuT6iiRTuTSS6JXW2JeaD9WA/0U7epnYgGLyEVD/v/WFt9hZLBRUh
r6eyCuK5t6IqVQ610/I37smTUnExODqOjBpcVUKm7etAWiT6XBmRTC9DSst97B4z
wm2f8Y8heJH7aP3sL5utkveB9WbRGXbFi/3deoFLHG9PA+RsiFsQf5Gg0Qj3DC4h
q47hjM8+AodcJp6ZxX3VljwIsLTAHozqyBQyoDc3rQKBgQD3wBUX1+V9WxkHLWNW
W8DjHxl2k4arY0gROZCPtWQArHxg28hnAPSGROwYvWwIkEa3LhAFSa/0C448p88x
IznECVx0aN1J4W9dFblDboZaVck5aOGA+gIpRAtmySAoI9kQV4Atr4dhXTihB8SV
H9PBSqNLlno9+3725va1ONV1HwKBgQDrWDxo6Dukbv3K2Bs7yOn/DNEw/NfJvtb4
pvt8WK4XlwBc8AmKUjqYC++ibDHnNBeR1SINHxk33qV6xWXooILqi/zM5yyRzBJV
P7HDCKIhhI28+9VAIBsJ9AdYJr7hjRLtxHT+nX/VNstejEoudggaxioaeY1Vtb7X
UeaL0h2iTwKBgQCJs5+FsyAAvsN4c8fE1hatpjl26KRvWi1SNZad6Yn9veEbzMzk
Q2mlv2UikxYa5GYJpnaNGdnMYSfbmsHUY+nVhgZ3RVnJmJ1XNZ3VVvch+pBvclX0
ZAETgph7tspCxTn+lUPPIMK0YSX6iuC+qgP+aUe92ZN0I/b7sH/rVf1+rQKBgAFf
LEr4P5C/zN7nz5DTpPmFm5qLfr6ATER6xLB+29TrXmcsRwH1ZL4KI8VwmAHe/dwt
v9sPuVfoBlLm36cxeFHhqwGOv2XCKMEyc9jNLhS/7wuQ9DdBeKbgM0LCRw6NgfS8
1mm9hUc64IiWjMAkk/uD+C7bUoWTX59lrNBX0zBlAoGAYNaJN8Qd+Q8f8ptP2Uwh
DqE/cuBacFwaeJszSC7vUEUAc/ST6eyeDT6lPhDcF3IIEBqeJhHv0BCOFeGulCJk
Mx29FZpyFfG7D0BFf7PJjcLkjSk2P7eIx0egzaMQphcOCLQvQJMVzal8HQBQ3eOe
MS/VlmIsdspwGM68YUSnzHU=
-----END PRIVATE KEY-----"""


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

